<?php

namespace App\Http\Controllers;
use App\MATRICE;
use App\FRMATRICE;
use App\FRPARTENARIAT;
use Illuminate\Http\Request;

class MATRICEController extends Controller
{
  public function view($ID_MATRICE){
    $ID_MATRICE= \DB::table('frmatrice')->where('ID_MATRICE')->get();
    return view('frmatrice', ['MATRICE'=>$ID_MATRICE]);
  }


  public function savematrice(){
    $FRPROJET = new FRPROJET();
    $FRPROJET->ID_PROJET = Input::get('ID_PROJET');
    $FRPROJET->TITREPROJET = Input::get('TITREPROJET');
    $FRPROJET->LIBELLEPROJET= Input::get('LIBELLEPROJET');
    $FRPROJET->save();



      $FRSEGMENTSCLIENTS = new FRSEGMENTSCLIENTS();
      $FRSEGMENTSCLIENTS->ID_SEGMENTS = Input::get('ID_SEGMENTS');
      $FRSEGMENTSCLIENTS->TITRESEGMENTS = Input::get('TITRESEGMENTS');
      $FRSEGMENTSCLIENTS->TYPESEGMENTS = Input::get('TYPESEGMENTS');
    //  $FRSEGMENTSCLIENTS->LIBELLEPROJET= Input::get('LIBELLEPROJET');
      $FRSEGMENTSCLIENTS->CONTENUSEGMENTS= Input::get('CONTENUSEGMENTS');
      $FRSEGMENTSCLIENTS->save();


      $FRCANAUX = new FRCANAUX();
      $FRCANAUX->ID_CANAUX = Input::get('ID_CANAUX');
      $FRCANAUX->TITRECANAUX = Input::get('TITRECANAUX');
    //  $FRSEGMENTSCLIENTS->LIBELLEPROJET= Input::get('LIBELLEPROJET');
      $FRCANAUX->CONTENUCANAUX= Input::get('CONTENUCANAUX');
      $FRCANAUX->RECONNAISSANCE= Input::get('RECONNAISSANCE');
      $FRCANAUX->EVALUATION= Input::get('EVALUATION');
      $FRCANAUX->ACHAT= Input::get('ACHAT');
      $FRCANAUX->PRESTATION= Input::get('PRESTATION');
      $FRCANAUX->VENTE= Input::get('VENTE');
      $FRCANAUX->save();

      $FRPROPOSITIONSDEVALEUR = new FRPROPOSITIONDEVALEUR();
      $FRPROPOSITIONSDEVALEUR->ID_PROPOSITIONS = Input::get('ID_PROPOSITIONDEVALEUR');
      $FRPROPOSITIONSDEVALEUR->TITREPROPOSITIONSDEVALEUR = Input::get('TITREPROPOSITIONSDEVALEUR');
      $FRPROPOSITIONSDEVALEUR->CONTENUPROPOSITIONSDEVALEUR = Input::get('CONTENUPROPOSITIONSDEVALEUR');
      $FRPROPOSITIONSDEVALEUR->TYPEPROPOSITIONSDEVALEUR = Input::get('TYPEPROPOSITIONDEVALEUR');
      $FRPROPOSITIONDEVALEUR->save();

      $FRSOURCESDEREVENUS = new FRSOURCESDEREVENUS();
      $FRSOURCESDEREVENUS->ID_SOURCESDEREVENUS = Input::get('ID_SOURCESDEREVENUS');
      $FRSOURCESDEREVENUS->TITRESOURCESDEREVENUS = Input::get('TITRESOURCESDEREVENUS');
      $FRSOURCESDEREVENUS->TYPESOURCESDEREVENU= Input::get('TYPESOURCESDEREVENU');

    //  $FRSEGMENTSCLIENTS->LIBELLEPROJET= Input::get('LIBELLEPROJET');
      $FRSOURCESDEREVENUS->CONTENUSOURCESDEREVENUS= Input::get('CONTENUSOURCESDEREVENUS');
      $FRSOURCESDEREVENUS->PRIXFIXE= Input::get('PRIXFIXE');
      $FRSOURCESDEREVENUS->PRIXVARIABLE= Input::get('PRIXVARIABLE');
      $FRSOURCESDEREVENUS->save();

      $FRRESSOURCESCLES = new FRRESSOURCESCLES();
      $FRRESSOURCESCLES->ID_RESSOURCESCLES = Input::get('ID_RESSOURCESCLES');
      $FRRESSOURCESCLES->TITRERESSOURCESCLES = Input::get('TITRERESSOURCESCLES');
    //  $FRSEGMENTSCLIENTS->LIBELLEPROJET= Input::get('LIBELLEPROJET');
      $FRRESSOURCESCLES->CONTENURESSOURCESCLES= Input::get('CONTENURESSOURCESCLES');
      $FRRESSOURCESCLES->TYPEPHYSIQUES= Input::get('TYPEPHYSIQUES');
      $FRRESSOURCESCLES->TYPEINTELLECTUELLES= Input::get('TYPEINTELLECTUELLES');
      $FRRESSOURCESCLES->TYPEHUMAINES= Input::get('TYPEHUMAINES');
      $FRRESSOURCESCLES->TYPEFINANCIERES= Input::get('TYPEFINANCIERES');
      $FRRESSOURCESCLES->save();

      $FRACTIVITESCLES = new FRACTIVITESCLES();
      $FRACTIVITESCLES->ID_ACTIVITESCLES = Input::get('ID_ACTIVITESCLES');
      $FRACTIVITESCLES->TITREACTIVITESCLES = Input::get('TITREACTIVITESCLES');
      $FRACTIVITESCLES->TYPEACTIVITESCLES = Input::get('TYPEACTIVITESCLES');

    //  $FRSEGMENTSCLIENTS->LIBELLEPROJET= Input::get('LIBELLEPROJET');
      $FRACTIVITESCLES->CONTENUACTIVITESCLES= Input::get('CONTENUACTIVITESCLES');
      $FRACTIVITESCLES->save();


      $FRPARTENARIAT = new FRPARTENARIAT();
      $FRPARTENARIAT->ID_PARTENARIAT = Input::get('ID_PARTENARIAT');
      $FRPARTENARIAT->TITREPARTENARIAT = Input::get('TITREPARTENARIAT');
      $FRPARTENARIAT->TYPEPARTENARIAT= Input::get('TYPEPARTENARIAT');
    //  $FRSEGMENTSCLIENTS->LIBELLEPROJET= Input::get('LIBELLEPROJET');
      $FRPARTENARIAT->CONTENUPARTENARIAT= Input::get('CONTENUPARTENARIAT');
      $FRPARTENARIAT->save();

      $FRSTRUCTUREDECOUTS=App\FRSTRUCTUREDECOUTS::all();
      $FRSTRUCTUREDECOUTS = new FRSTRUCTUREDECOUTS();
      $FRSTRUCTUREDECOUTS->ID_STRUCTUREDECOUTS = Input::get('ID_STRUCTUREDECOUTS');
      $FRSTRUCTUREDECOUTS->TITRESTRUCTUREDECOUTS = Input::get('TITRESTRUCTUREDECOUTS');
      $FRSTRUCTUREDECOUTS->TYPESTRUCTUREDECOUTS = Input::get('TYPESTRUCTUREDECOUTS');
    //  $FRSEGMENTSCLIENTS->LIBELLEPROJET= Input::get('LIBELLEPROJET');
      $FRSTRUCTUREDECOUTS->CONTENUSTRUCTUREDECOUTS= Input::get('CONTENUSTRUCTUREDECOUTS');
      $FRSTRUCTUREDECOUTS->COUTSFIXES= Input::get('COUTSFIXES');
      $FRSTRUCTUREDECOUTS->COUTSVARIABLES= Input::get('COUTSVARIABLES');
      $FRSTRUCTUREDECOUTS->ECONOMIESDECHELLES= Input::get('ECONOMIESDECHELLES');
      $FRSTRUCTUREDECOUTS->ECONOMIESENVERGURE= Input::get('ECONOMIESENVERGURE');
      $FRSTRUCTUREDECOUTS->save();

      $FRRELATIONCLIENT = new FRRELATIONCLIENT();
      $FRRELATIONCLIENT->ID_RELATIONCLIENT = Input::get('ID_RELATIONCLIENT');
      $FRRELATIONCLIENT->TITRERELATIONCLIENT = Input::get('TITRERELATIONCLIENT');
      $FRRELATIONCLIENT->TYPERELATIONCLIENT= Input::get('TYPERELATIONCLIENT');
    //  $FRSEGMENTSCLIENTS->LIBELLEPROJET= Input::get('LIBELLEPROJET');
      $FRPARTENARIAT->CONTENURELATIONCLIENT= Input::get('CONTENURELATIONCLIENT');
      $FRPARTENARIAT->save();

  }

  public function editPartenaires(Request $request)
  {
    $validationForm = true;

    if ($validationForm) {

      // enregistrement en bdd et action de modifier dans la basse de donnée avec une matrice existant
    
      $FRPARTENARIAT = new FRPARTENARIAT;
      $FRPARTENARIAT->TITREPARTENARIAT = $request->TITREPARTENARIAT;

      $FRPARTENARIAT->TYPEPARTENARIAT = $request->TYPEPARTENARIAT;
      $FRPARTENARIAT->CONTENUPARTENARIAT = $request->CONTENUPARTENARIAT;

      $FRPARTENARIAT->save();




      $response = ['status' => 'modifier dans base de donnéee'];

    }

    return \Response::json($FRPARTENARIAT);
  }


}
