<?php

namespace App\Http\Controllers;
use App\MATRICE;
use Illuminate\Http\Request;

class MATRICE extends Controller
{
  public function savematrice(){
    $FRPROJET = new FRPROJET();
    $FRPROJET->ID_PROJET = Input::get('ID_PROJET');
    $FRPROJET->TITREPROJET = Input::get('TITREPROJET');
    $FRPROJET->LIBELLEPROJET= Input::get('LIBELLEPROJET');



      $FRSEGMENTSCLIENTS = App\FRSEGMENTSCLIENTS::all();
      $FRCANAUX=App\FRRELATIONCLIENT::all();
      $FRPROPOSITIONSDEVALEUR=App\FRPROPOSITIONSDEVALEUR::all();
      $FRSOURCESDEREVENUS=App\FRSOURCESDEREVENUS::all();
      $FRRESSOURCESCLES=App\FRRESSOURCESCLES::all();
      $FRACTIVITESCLES=App\FRACTIVITESCLES::all();
      $FRPARTENARIAT=App\FRPARTENARIAT::all();
      $FRSTRUCTUREDECOUTS=App\FRSTRUCTUREDECOUTS::all();
  }
}
